//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SuperWord.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SuperWord_DIALOG            102
#define IDSFN_WORD_CMD                  102
#define IDS_DATABASE                    103
#define IDD_CONDSETDLG                  104
#define IDSFN_WORD_FILTER               104
#define IDSFN_GLOBAL_CMD                105
#define IDSP_WORD_CLASS                 107
#define IDSP_RECITE_SCHEME              108
#define IDSFN_CFG                       109
#define IDSP_WORD_FILTER                111
#define IDSP_WORD_CMD                   112
#define IDSP_GLOBAL_CMD                 113
#define IDR_MAINFRAME                   128
#define IDR_ACCEL                       129
#define IDR_MAINMENU                    131
#define IDI_OPTION                      132
#define IDI_REVIEW_TODAY                133
#define IDI_REVIEW_ALL                  134
#define IDB_CHECK_RIGHT                 135
#define IDB_CHECK_WRONG                 136
#define IDI_ICON1                       137
#define IDD_COLOR_PAGE                  139
#define IDD_CS_WORD_DLG                 142
#define IDR_FILTERSETMENU               143
#define IDD_CS_MEANING_DLG              144
#define IDD_CS_PHONETIC_DLG             145
#define IDD_CS_CLASS_DLG                146
#define IDD_CS_ACCESSTIME_DLG           148
#define IDD_RS_ACCESSTIME_PAGE          149
#define IDB_FILTER                      151
#define IDB_OPTION                      152
#define IDD_CS_TYPE_DLG                 154
#define IDD_WORDTYPE_DLG                155
#define IDB_FILTER_SMALL                156
#define IDD_RGN_DLG                     158
#define IDD_INPUT_DLG                   159
#define IDB_OPTION_SMALL                160
#define IDB_MENU_SMALL                  161
#define IDB_MENU                        162
#define IDD_POPUP_DLG                   163
#define IDD_RS_MISC_PAGE                166
#define IDD_PROGRESS_DLG                168
#define IDI_OR                          169
#define IDI_NOT                         170
#define IDI_AND                         171
#define IDI_MEANING                     172
#define IDI_WORD                        173
#define IDD_TEST_DLG                    174
#define IDD_RS_COLOR_PAGE               175
#define IDD_TRANS_IMG_DLG               176
#define IDD_PRACTISE_RESULT_DLG         177
#define IDR_SCRIPT_FOR_LINA             179
#define IDI_PHONETIC                    180
#define IDI_CLASS                       181
#define IDI_TYPE                        182
#define IDI_RUNNING                     183
#define IDI_ACCESS_TIME                 184
#define IDR_HTML_MEANING_TEMPLATE       185
#define IDIMG_CHK_RIGHT                 189
#define IDIMG_CHK_WRONG                 190
#define IDIMG_HEART                     191
#define IDIMG_GOLD_FISH                 192
#define IDD_HAPPY_BIRTHDAY              193
#define IDB_LINA                        195
#define IDB_EARTH                       198
#define IDF_PHONETIC                    203
#define IDC_CURSOR_COPY                 205
#define IDC_CURSOR2                     206
#define IDC_CURSOR_MOVE                 206
#define IDD_DIALOG1                     207
#define IDD_CS_INTERVAL_DLG             207
#define IDD_CS_HOTKEY_DLG               208
#define IDD_CS_MOVEWORD_DLG             209
#define IDD_CS_SETCOLOR_DLG             210
#define IDD_CS_REMARK_DLG               211
#define IDD_CS_OPENDLG_DLG              213
#define IDD_CS_SHOW_ELEMENT_DLG         214
#define IDD_CS_WORDTYPE_DLG             215
#define IDD_CS_MISC_DLG                 216
#define IDD_CS_ACCEL_DLG                217
#define IDI_ICON_PLUS                   218
#define IDD_RECITE_SCHEME               219
#define IDD_CS_LOAD_RECITE_SCHEME_DLG   220
#define IDI_SERIES_CMD                  221
#define IDI_HOTKEY_CMD                  222
#define IDI_TIMER_CMD                   223
#define IDI_MISC_CMD                    226
#define IDI_RANDOM_CMD                  227
#define IDI_IF_CMD                      228
#define IDI_SHOWELEMENT_CMD             229
#define IDI_OPENDLG_CMD                 231
#define IDI_SETWORDTYPE_CMD             232
#define IDI_SETCOLOR_CMD                233
#define IDI_MOVEWORD_CMD                235
#define IDI_LOADCOMP_CMD                236
#define IDI_FILTER                      237
#define IDI_GLOBAL_CMD                  238
#define IDI_PERWORD_CMD                 239
#define IDD_DIALOG2                     240
#define IDD_CS_MISC_COND_DLG            240
#define IDD_GLOBALCMD_SET_DLG           241
#define IDC_RICHEDIT_WORD               1000
#define IDC_RICHEDIT_EXPLAIN            1001
#define IDC_PROGRESS                    1002
#define IDC_RICHEDIT_PRACTISE           1003
#define IDC_EDIT_RETURNNUM              1023
#define IDC_BTN_DLGBK                   1038
#define IDC_BTN_WORDBK                  1039
#define IDC_BTN_WORDCOLOR               1040
#define IDC_BTN_PRACTICEBK              1041
#define IDC_FILTERTREE                  1041
#define IDC_BTN_PRICTICECOLOR           1042
#define IDC_EDIT_MATCHER                1042
#define IDC_BTN_MEANINGBK               1043
#define IDC_CHECK_USEREGEX              1043
#define IDC_BTN_PHONETICSCOLOR          1044
#define IDC_RICHEDIT_MATCHER            1044
#define IDC_BTN_MEANINGCOLOR            1045
#define IDC_BTN_TYPEBK                  1046
#define IDC_PHONETIC_AREA               1047
#define IDC_BTN_TYPEACTIVE              1047
#define IDC_BTN_TYPEBORDER              1048
#define IDC_BTN_ACCESSTIMEBK            1049
#define IDC_COMBO_CLASSLIST             1050
#define IDC_BTN_ACCESSTIMECOLOR         1050
#define IDC_COMBO_COLOR_ELEMENT         1050
#define IDC_RADIO_WORD_TIMER            1051
#define IDC_BTN_PROGRESSCR1             1051
#define IDC_RADIO_WORD_TAB              1052
#define IDC_BTN_PROGRESSBK              1052
#define IDC_EDIT_WORDTIMER_DELAY        1053
#define IDC_EDIT                        1053
#define IDC_BTN_PROGRESSCHAR            1053
#define IDC_STATIC_USEABSDATE           1054
#define IDC_RADIO_MEANING_TIMER         1054
#define IDC_BTN_PROGRESSCR2             1054
#define IDC_STATIC_USERELADATE          1055
#define IDC_RADIO_MEANING_TAB           1055
#define IDC_BTN_MS_FACE                 1055
#define IDC_DATETIMEPICKER_TMMIN        1056
#define IDC_EDIT_MEANINGTIMER_DELAY     1056
#define IDC_BTN_MS_ARROW                1056
#define IDC_DATETIMEPICKER_TMMAX        1057
#define IDC_BTN_MS_SHADOW               1057
#define IDC_EDIT_DAYBEFORE              1058
#define IDC_BTN_MS_DARKSHADOW           1058
#define IDC_CHECK_TMMIN                 1059
#define IDC_BTN_MS_BASE                 1059
#define IDC_CHECK_TMMAX                 1060
#define IDC_BTN_MS_HIGHLIGHT            1060
#define IDC_RADIO_ATS_METHOD            1061
#define IDC_BUTTON_ALLRECITED           1062
#define IDC_BTN_IMPORT_FILTER           1064
#define IDC_BTN_EXPORT_FILTER           1065
#define IDC_BTN_MENU                    1069
#define IDC_COMBO_TYPELIST              1073
#define IDC_BTN_MOVEUP                  1075
#define IDC_WORDTYPE                    1075
#define IDC_BTN_MOVEDOWN                1076
#define IDC_HOTKEY                      1077
#define IDC_PROMPT                      1078
#define IDC_BTN_ADD_WORD_TYPE           1079
#define IDC_BTN_DEL_WORD_TYPE           1080
#define IDC_BTN_SET_HOT_KEY             1081
#define IDC_BTN_EXCHANGE_SEL            1082
#define IDC_ACCESS_DATE                 1084
#define IDC_RADIO_MARKACCESS_WHEN_TYPE  1085
#define IDC_RADIO_MARKACCESS_WHEN_TYPERIGHT 1086
#define IDC_RADIO_MARKACCESS_WHEN_TYPEWRONG 1087
#define IDC_CB_MARK_ACCESSTIME_MODE     1088
#define IDC_CHECK_SHOW_DETAIL_MEANING   1089
#define IDC_RADIO_WORD_ORDER_ASC        1090
#define IDC_BTN_LOAD_COLORSCHEME        1095
#define IDC_BTN_SAVE_COLORSCHEME        1096
#define IDC_HTML_MEANING                1099
#define IDC_BUTTON1                     1101
#define IDC_BTN_SET_COLOR               1101
#define IDC_BUTTON_SAVE_RECITE_SCHEME   1101
#define IDC_BUTTON2                     1102
#define IDC_STATIC_CHILD                1103
#define IDC_STATIC_LOGO                 1103
#define IDC_BUTTON_OPEN_RECITE_SCHEME   1103
#define IDC_COLOR_CHILD                 1104
#define IDC_CB_WORD_ORDER_BASE          1105
#define IDC_CB_WORD_ORDER               1106
#define IDC_CHECK_MOVENEXT_WHEN_TYPE_RIGHT 1107
#define IDC_CHECK_SHOW_PRACTISE_WND     1108
#define IDC_EDIT_WORD_CLASS             1109
#define IDC_BTN_SELECT_WORD_CLASS       1110
#define IDC_STATIC_ICON                 1112
#define IDC_STATIC_CONGRATULATION       1113
#define IDC_STATIC_FLY                  1115
#define IDC_STATIC_INFO                 1116
#define IDC_EDIT_AUTOMARK_ACCESS_TIME_DELAY 1117
#define IDC_STATIC_AUTOMARK_ACCESS_TIME_DELAY 1118
#define IDC_TESTTREE                    1120
#define IDC_TREE1                       1121
#define IDC_TREE_PERWORD_CMD            1121
#define IDC_TREE_GLOBAL_CMD             1122
#define IDC_CHECK_MATCH_DETAIL_MEANING  1123
#define IDC_TREE_CONDITION              1123
#define IDC_EDIT_INTERVAL               1124
#define IDC_COMBO_MOVEWORD_CMD          1126
#define IDC_EDIT_COMP_REMARK            1129
#define IDC_COMBO_REPEAT_TIME           1130
#define IDC_CHECK_DELETE_ON_WORD_CHANGE 1131
#define IDC_COMBO_DIALOG                1133
#define IDC_COMBO_VISUAL_ELEMENT        1134
#define IDC_RADIO_SHOW_WORD             1135
#define IDC_RADIO_HIDE_WORD             1136
#define IDC_COMBO_WORD_TYPE             1137
#define IDC_RADIO_SET_WORD_TYPE_STYLE   1138
#define IDC_RADIO2                      1139
#define IDC_RADIO3                      1140
#define IDC_COMBO_MISC_CMD              1141
#define IDC_CHECK_CONTROL               1142
#define IDC_CHECK_ALT                   1143
#define IDC_CHECK_SHIFT                 1144
#define IDC_COMBO_VIRTUAL_KEY           1145
#define IDC_CHECK_SHOW_CONDITION        1148
#define IDC_CHECK_SHOW_GLOBAL_CMD       1149
#define IDC_CHECK_SHOW_PERWORD_CMD      1150
#define IDC_STATIC_SEPARATOR            1151
#define IDC_EDIT_RECITE_SCHEME_FILE     1153
#define IDC_COMBO_MISC_CONDITION        1154
#define IDC_NEXTWORD                    32771
#define IDC_PREVWORD                    32772
#define ID_ABOUD                        32777
#define ID_OPTION                       32778
#define IDC_FIRSTWORD                   32783
#define IDC_LASTWORD                    32784
#define ID_BROSE_RANDOM                 32785
#define ID_WORD_CLASS                   32793
#define IDSFN_DETAIL_MEANING            32794
#define ID_SET_FILTER                   32795
#define IDSFN_WORD_TYPE                 32795
#define ID_CHECK_PRICTICE_WORD          32796
#define IDC_WORDTYPE_LIST               32796
#define ID_MEANING_SETFONT              32797
#define IDS_PHONETIC_FONT_NAME          32797
#define ID_MEANING_SHOWDETAIL           32798
#define IDSP_COLOR_SCHEME               32798
#define ID_BROWSE_DIRECT                32799
#define IDSFN_USER_WORD                 32799
#define ID_WORD_FONT                    32800
#define IDC_ADDFILTER                   32801
#define IDFS_ADD_WORD_FILTER            32804
#define IDFS_ADD_MEANING_FILTER         32805
#define IDFS_ADD_AND_FILTER             32806
#define IDFS_ADD_OR_FILTER              32807
#define IDFS_ADD_NOT_FILTER             32808
#define IDFS_EDIT_FILTER                32811
#define IDFS_DELETE_FILTER              32812
#define IDFS_ADD_PHONETIC_FILTER        32813
#define IDFS_ADD_CLASS_FILTER           32814
#define IDFS_FILTER_TO_WORD             32816
#define IDFS_FILTER_TO_MEANING          32818
#define IDFS_FILTER_TO_PHONETIC         32819
#define IDFS_FILTER_TO_CLASS            32820
#define IDFS_FILTER_TO_AND              32821
#define IDFS_FILTER_TO_OR               32822
#define IDFS_FILTER_TO_NOT              32823
#define IDFS_ADD_ACCESSTIME_FILTER      32824
#define IDFS_FILTER_TO_ACCESSTIME       32825
#define IDACC_SHOW_WORDMEANING          32826
#define IDFS_ADD_TYPE_FILTER            32827
#define IDFS_FILTER_TO_TYPE             32828
#define ID_MANAGE_WORDTYPE              32835
#define ID_SET_ACCESS_TIME              32836
#define IDC_TOGGLE_WORDTYPE_1           32840
#define ID_RESET_COLORS                 32860
#define ID_FILTER_EXPAND_ALL            32861
#define ID_UNSET_ACCESS_TIME            32862
#define ID_TRANSLATE_ACCEL              32863
#define ID_TOGGLE_WORD_DETAIL_MEANING   32864
#define ID_HIDE_PRACTISE_RESULT_DLG     32866
#define ID_SET_GLOBAL_COMMAND           32870
#define ID_SET_PERWORD_COMMAND          32871
#define ID_SET_RECITE_SCHEME            32878
#define ID_32879                        32879
#define ID_SET_GLOBAL_CMD               32880
#define ID_32881                        32881
#define ID_TOOGLE_ACCESS_TIME           32882

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        242
#define _APS_NEXT_COMMAND_VALUE         32883
#define _APS_NEXT_CONTROL_VALUE         1155
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
